name: parquez
functions:
- url: validate-input.py
  name: validate
  kind: job
  image: aviaigz/parquez
- url: get_table_schema.py
  name: get_schema
  kind: job
  image: aviaigz/parquez
- url: create_parquet_table.py
  name: create_parquet
  kind: job
  image: aviaigz/parquez
- url: create_kv_view.py
  name: create_kv_view
  kind: job
  image: aviaigz/parquez
- url: create_unified_view.py
  name: create_unified_view
  kind: job
  image: aviaigz/parquez
- url: run_parquez_interval.py
  name: run_parquez_interval
  kind: job
  image: aviaigz/parquez
- url: run_scheduler.py
  name: run_scheduler
  kind: job
  image: aviaigz/parquez
workflows:
- name: main
  path: workflow.py
artifacts: []
